export const CLOSE_SELECT_BLOCK = 'close_select_block'
export const OPEN_CALENDAR_PICKER = 'open_calendar_picker'
export const UPDATE_MONTH_OR_YEAR = 'update_month_or_year'
export const OPEN_DATETIME_PICKER = 'open_datetime_picker'
export const UPDATE_TIME_VALUE = 'update_time_value'
export const UPDATE_CURRENT_DATE = 'update_current_date'
export const INITIALIZE_YEAR_ARRAY = 'initialize_year_array'
export const INITIALIZE_WEEKS_ARRAY = 'initialize_weeks_array'
